[[snippets]]
  command = "echo | openssl s_client -connect `hostname`:443 2> /dev/null | openssl x509 -noout -dates"
  description = "Show expiration date of SSL certificate"
[[snippets]]
  command = "carthage update --platform iOS"
  description = "Update carthage library only iOS"
[[snippets]]
  command = "sudo-vim /etc/dnsmasq.host"
  description = "Edit dnsmasq.host"
[[snippets]]
  command = "sudo /etc/init.d/dnsmasq restart"
  description = "Restart dnsmasq"
[[snippets]]
  command = "emulator -avd `emulator -list-avds | fzf` -dns-server <IP>"
  description = "Start Android emulator which use DNS server"
